---
layout: cv
title: David Martinez's CV
---
# David Martinez
Software Engineering & Data Science Student

<div id="webaddress">
<a href="mailto:dmar06b@gmail.com">dmar06b@gmail.com</a>
| <a href="https://www.linkedin.com/in/dmar06b">LinkedIn Profile</a>
| <a href="https://github.com/DMartinez06B">GitHub Profile</a>
</div>

## Profile

A proactive person at solving problems with patience, a sharp vision, and attention in situations under pressure. Fast learning, responsible, organized, and focused on results. Generator of ideas and good interpersonal relationships.

## Education

`September 2022 - Present`
__Brigham Young University - Idaho__, Rexburg, Idaho

- Bachelor of Science Software Engineering - Minor in QA
- Expected Graduation: April 2027
- GPA: 3.1

`January 2016 - September 2016`
__Institute CAPSES__, Santa Cruz, Bolivia

- Repair and maintenance of smartphones (software/hardware)

## Experience

`Current`
__CIT Lab Secretary and Tutor__
*Brigham Young University - Idaho (Rexburg, Idaho)*

- Volunteer as a tutor, helping students with general programming and troubleshooting.
- Supported overseeing operations, assisted in finding tutors, and advertising the lab.
- Simplified registration and check-in time by reducing the time and steps needed in half.

`Past`
__International Mentor__
*HEBER J. GRANT Mentoring (Rexburg, Idaho)*

- Supported emotionally and guided students, addressing concerns and helping navigate cultural differences.
- Provided knowledge of resources available on campus, including counseling services, academic support, and extracurricular activities.

`Past`
__Technician and Seller of Smartphones__
*Arca de Noe Smartphones (Santa Cruz, Bolivia)*

- Increased sales in general, especially in premium cell phone models, by double the sales.
- Built trust and reliance in-store through good customer service and strong smartphone knowledge.

## Skills & Tools

### Skills
- Python, C#, Java, HTML, CSS, SQL, JavaScript, Dart, DAX
- Debugging, Technical support
- Computer & Smartphone software/hardware maintenance
- Leadership, Teaching, and Multitasking
- PowerBI, GitHub

### Tools
- VS Code
- JetBrains Rider
- LM Studio
- Antigravity